### ISSUE TITLE
Code usage example

### ISSUE THREAD

**Issue by siko1056** [walterfm/signs#1]
Thank you very much @walterfm for the article <https://arxiv.org/abs/2109.07838> for computing the sum of products:

<img src="https://render.githubusercontent.com/render/math?math=S = \displaystyle\sum_{i = 1}^{n}\prod_{j = 1}^{n_i} a_{ij}">

Was it possible to give a small example how to use `quick_sign` and `float_sign` with the following 10x4 input matrices?  For example I added to the end of `float_sign_sample.cpp` the following code

```cc
float* A = new float[10 * 4];

// Initialize A ....

// Already done in the file "float_sign_sample.cpp" before.
// wm::quick_sign<float> quick;
// wm::float_sign<float> robust;

for (int i = 0; i < 10; i++)
  for (int j = 0; j < 4; j++)
    {
      quick.add<1>  ( A[i + j * 10] );  //  <-- Error
      robust.add<1> ( A[i + j * 10] );
    }

std::cout << "quick_sign = " << quick.sign () << std::endl;
std::cout << "robust_sign = " << robust.sign () << std::endl;

quick.clear();
robust.clear();
```
The error with GCC 11.2 on Linux is:

```
float_sign.hpp: In instantiation of 'void wm::quick_sign<T>::add(const T&, const X& ...) [with int Sign = 1; X = {}; T = float]':
float_sign_sample.cpp:77:21:   required from here
float_sign.hpp:195:23: error: no matching function for call to 'wm::quick_sign<float>::add_impl<sign>(float, const float&)'
  195 |         add_impl<sign>(-a, a, x...);
      |         ~~~~~~~~~~~~~~^~~~~~~~~~~~~
float_sign.hpp:206:10: note: candidate: 'template<int Sign, class ... X> void wm::quick_sign<T>::add_impl(T, T, const T&, const X& ...) [with int Sign = Sign; X = {X ...}; T = float]'
  206 |     void add_impl(T md, T u, T const& a, X const&... x) //  u = |a0 ... ak| + ek
      |          ^~~~~~~~
float_sign.hpp:206:10: note:   template argument deduction/substitution failed:
float_sign.hpp:195:23: note:   candidate expects at least 3 arguments, 2 provided
  195 |         add_impl<sign>(-a, a, x...);
      |         ~~~~~~~~~~~~~~^~~~~~~~~~~~~
float_sign.hpp:199:26: error: no matching function for call to 'wm::quick_sign<float>::add_impl<(-1)>(const float&, float)'
  199 |           add_impl<-sign>(a, -a, x...);
      |           ~~~~~~~~~~~~~~~^~~~~~~~~~~~~
float_sign.hpp:206:10: note: candidate: 'template<int Sign, class ... X> void wm::quick_sign<T>::add_impl(T, T, const T&, const X& ...) [with int Sign = Sign; X = {X ...}; T = float]'
  206 |     void add_impl(T md, T u, T const& a, X const&... x) //  u = |a0 ... ak| + ek
      |          ^~~~~~~~
float_sign.hpp:206:10: note:   template argument deduction/substitution failed:
float_sign.hpp:199:26: note:   candidate expects at least 3 arguments, 2 provided
  199 |           add_impl<-sign>(a, -a, x...);
      |           ~~~~~~~~~~~~~~~^~~~~~~~~~~~~
```

My impresion is that in the `quick_sign` class

https://github.com/walterfm/signs/blob/da8639afb0fa7148cf2534b6a6a90b2a01f8d2a6/float_sign.hpp#L177-L188

the symbols `a` and `-a` should not be parameters and rather should be associated with `u_` and `md_`, right?

**Comment by walterfm** [comment]
Dear Kai,

   Thanks for your interest in my article.

   Regarding your question, the way to compute the sum
S= sum_{i = 0}^9 prod_{j=0}^3 A[i + 10 * j]

would be

for (int i = 0; i < 10; i++) }
quick.add<1> ( A[i + 10 * j] , A[i + 10 * (j + 1)], A[i + 10 * (j + 2)] ,
A[i + 10 * (j + 3)] );
robust.add<1> (A[i + 10 * j] , A[i + 10 * (j + 1)], A[i + 10 * (j + 2)] ,
A[i + 10 * (j + 3)] );
}

which is reasonable. However, the way to compute the sum
S= sum_{i = 0}^3 prod_{j=0}^9 A[i + 4 * j]

would be

for (int i = 0; i < 4; i++) }
quick.add<1> ( A[i ] , A[i + 4], A[i + 8] , A[i + 12] , A[i + 16], A[i ] ,
A[i + 20], A[i + 24] , A[i + 28] , A[i + 32], , A[i + 36]);
robust.add<1> (A[i ] , A[i + 4], A[i + 8] , A[i + 12] , A[i + 16], A[i ] ,
A[i + 20], A[i + 24] , A[i + 28] , A[i + 32], , A[i + 36]);
}

which is bad, and would get unbearable for j_max much greater than 10.

For this reason, I rewrote the code so that it we could simply write:

wm::quick_by_rows(A, 10, 4)
and
robust.by_rows(A,10,4)

These changes are in the enclosed files, which also contain
the following improvements:

a) The code is now immune to "reasonable overflow", where by
reasonable I mean numbers with exponent smaller than 10^9.

b) there are now functions to compute the signs of determinants,
which were the original motivation for the article.

Your comments and suggestions about these files are welcome.
For this kind of code,  It takes time to get both the code and
its interface to a good state, and comments like yours
are very helpful.

    regards,

              walter.

**Comment by siko1056** [comment]
Thank you for the updates and examples @walterfm .  This is really helpful :slightly_smiling_face: If I face further problems, I will report back.

**Comment by walterfm** [comment]
Kai,
   Please note that there was a bug on my commit yesterday
(I was in a hurry, and forgot one unit test.) Now the bug
is fixed.
        walter.
